export const lightTheme = {
  backgroundColor: "#ffffff",
  surfaceWhiteColor: "#f8f8f8",
  surfaceBlueColor: "#e5f2ff",
  primaryColor: "#007aff",
  accentColor: "#007aff",
  bodyPrimaryColor: "#131313",
  bodyOnPrimaryColor: "#ffffff",
  bodySecondaryColor: "#d7d7d7",
  borderColor: "#f2f2f2",
  textColor: "#131313",
  primaryButtonColor: "#007aff",
  primaryButtonTextColor: "#ffffff",
  primaryButtonBorderColor: "transparent",
  primaryDisabledButtonColor: "#d7d7d7",
  primaryDisabledButtonTextColor: "#F2F2F2",
  primaryDisabledButtonBorderColor: "transparent",
  secondaryButtonColor: "#e5f2ff",
  secondaryButtonTextColor: "#131313",
  secondaryButtonBorderColor: "transparent",
  secondaryDisabledButtonColor: "#F8F8F8",
  secondaryDisabledButtonTextColor: "#D7D7D7",
  secondaryDisabledButtonBorderColor: "transparent",
  tertiaryButtonColor: "transparent",
  tertiaryButtonTextColor: "#007aff",
  tertiaryButtonBorderColor: "#007aff",
  tertiaryDisabledButtonColor: "transparent",
  tertiaryDisabledButtonTextColor: "#D7D7D7",
  tertiaryDisabledButtonBorderColor: "#D7D7D7",
  textButtonColor: "#007aff",
  textButtonDisabledColor: "#D7D7D7",
  disabledColor: "rgba(0, 0, 0, 0.4)",
  surfaceDisabledColor: "#f2f2f2",
  successColor: "#38AD49",
  errorColor: "#D53F36",
  successTextColor: "#ffffff",
  errorTextColor: "#ffffff",
  cardBackgroundColor: "#f8f8f8",
  secondaryTextColor: "#666666",
  transparentBackgroundColor: "rgba(0, 0, 0, 0.5)",
};

export const darkTheme = {
  backgroundColor: "#131313",
  surfaceBlackColor: "#262626",
  surfaceBlueColor: "#00254d",
  primaryColor: "#007aff",
  accentColor: "#007aff",
  bodyPrimaryColor: "#ffffff",
  bodyOnPrimaryColor: "#ffffff",
  bodySecondaryColor: "#4C4C4C",
  borderColor: "#393939",
  textColor: "#ffffff",
  primaryButtonColor: "#007aff",
  primaryButtonTextColor: "#ffffff",
  primaryButtonBorderColor: "transparent",
  primaryDisabledButtonColor: "#4C4C4C",
  primaryDisabledButtonTextColor: "#393939",
  primaryDisabledButtonBorderColor: "transparent",
  secondaryButtonColor: "#00254C",
  secondaryButtonTextColor: "#FFFFFF",
  secondaryButtonBorderColor: "transparent",
  secondaryDisabledButtonColor: "#262626",
  secondaryDisabledButtonTextColor: "#4C4C4C",
  secondaryDisabledButtonBorderColor: "transparent",
  tertiaryButtonColor: "transparent",
  tertiaryButtonTextColor: "#007aff",
  tertiaryButtonBorderColor: "#007aff",
  tertiaryDisabledButtonColor: "transparent",
  tertiaryDisabledButtonTextColor: "#4C4C4C",
  tertiaryDisabledButtonBorderColor: "#4C4C4C",
  textButtonColor: "#007aff",
  textButtonDisabledColor: "#4C4C4C",
  disabledColor: "rgba(255, 255, 255, 0.4)",
  surfaceDisabledColor: "#393939",
  successColor: "#38AD49",
  errorColor: "#D53F36",
  successTextColor: "#ffffff",
  errorTextColor: "#ffffff",
  cardBackgroundColor: "#262626",
  secondaryTextColor: "#A0A0A0",
  transparentBackgroundColor: "rgba(0, 0, 0, 0.5)",
};

